server {
    listen 80;
    server_tokens off;
    root /usr/share/nginx/html;
    access_log off;
    location /api/auth/ { proxy_pass http://identity:8000; proxy_set_header X-Request-ID $http_x_request_id; }
    location /api/tickets { proxy_pass http://tickets:8000; proxy_set_header X-Request-ID $http_x_request_id; }
    location /health/ { proxy_pass http://tickets:8000; }
    location = /docs { proxy_pass http://identity:8000; }
    location / { try_files $uri $uri/ /index.html; }
}
